package com.halawa.goodseasons.model.entity;

// Generated Jul 25, 2010 11:25:21 AM by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CampaignItem generated by hbm2java
 */
@Entity
@Table(name = "Campaign_Item")
public class CampaignItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2748586229237214522L;
	private Long id;
	private CampaignItemType campaignItemType;
	private Campaign campaign;
	private double quantity;
	private double minQuantity;
	private double maxQuantity;

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "item_type_id", nullable = false)
	public CampaignItemType getCampaignItemType() {
		return this.campaignItemType;
	}

	public void setCampaignItemType(CampaignItemType campaignItemType) {
		this.campaignItemType = campaignItemType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "campaign_id", nullable = false)
	public Campaign getCampaign() {
		return this.campaign;
	}

	public void setCampaign(Campaign campaign) {
		this.campaign = campaign;
	}

	@Column(name = "quantity", nullable = false, precision = 53, scale = 0)
	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	@Column(name = "min_quantity", nullable = false, precision = 53, scale = 0)
	public double getMinQuantity() {
		return this.minQuantity;
	}

	public void setMinQuantity(double minQuantity) {
		this.minQuantity = minQuantity;
	}

	@Column(name = "max_quantity", nullable = false, precision = 53, scale = 0)
	public double getMaxQuantity() {
		return this.maxQuantity;
	}

	public void setMaxQuantity(double maxQuantity) {
		this.maxQuantity = maxQuantity;
	}
}
