package com.halawa.goodseasons.model.entity;

// Generated Jul 25, 2010 11:25:21 AM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Type;

/**
 * CampaignItemType generated by hbm2java
 */
@Entity
@Table(name = "Campaign_Item_Type", uniqueConstraints = @UniqueConstraint(columnNames = {
		"name", "case_type" }))
public class CampaignItemType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7221643995375407261L;
	private int id;
	private String name;
	private short caseType;
	private Integer percentage;
	/**
	 * This flag used to define if the item will use the needy case monthly amount to calculated the item value or not
	 */
	private boolean monthlyBased;
	/** 
	 * This flag define if this item type should be default for all campaigns, so it will be added by default as item to new campaigns.
	 */
	private boolean defaultItem;
	private boolean allowPending;
	private String unitName;
	private short accumulationType;
	private Set<CampaignItem> campaignItems = new HashSet<CampaignItem>(0);

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "case_type", nullable = false)
	public short getCaseType() {
		return this.caseType;
	}

	public void setCaseType(short caseType) {
		this.caseType = caseType;
	}

	@Column(name = "percentage")
	public Integer getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Integer percentage) {
		this.percentage = percentage;
	}
	
	@Column(name="relative_to_monthly_amount", insertable=false, updatable=false)
	@Type(type="yes_no")
	public boolean isMonthlyBased() {
		return monthlyBased;
	}

	public void setMonthlyBased(boolean monthlyBased) {
		this.monthlyBased = monthlyBased;
	}
	
	
	@Column(name="default_item", insertable=false, updatable=false)
	@Type(type="yes_no")
	public boolean isDefaultItem() {
		return defaultItem;
	}

	public void setDefaultItem(boolean defaultItem) {
		this.defaultItem = defaultItem;
	}
	
	@Column(name="allow_pending", insertable=false, updatable=false)
	@Type(type="yes_no")
	public boolean isAllowPending() {
		return allowPending;
	}

	public void setAllowPending(boolean allowPending) {
		this.allowPending = allowPending;
	}

	@Column(name="unit_name", insertable=false, updatable=false)
	public String getUnitName() {
		return unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "campaignItemType")
	public Set<CampaignItem> getCampaignItems() {
		return this.campaignItems;
	}

	public void setCampaignItems(Set<CampaignItem> campaignItems) {
		this.campaignItems = campaignItems;
	}


	@Column(name = "accumulation_type", nullable = false)
	public short getAccumulationType() {
		return accumulationType;
	}

	public void setAccumulationType(short accumulationType) {
		this.accumulationType = accumulationType;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CampaignItemType other = (CampaignItemType) obj;
		if (id != other.id)
			return false;
		return true;
	}
}
