package com.halawa.goodseasons.model.entity;

// Generated Jul 25, 2010 11:25:21 AM by Hibernate Tools 3.2.5.Beta

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CampaignAction generated by hbm2java
 */
@Entity
@Table(name = "Campaign_Action", uniqueConstraints = @UniqueConstraint(columnNames = {
		"case_id", "campaign_id" }))
public class CampaignAction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8997467453492146112L;
	private Long id;
	private Campaign campaign;
	private User user;
	private NeedyCase needyCase;
	private Date addingDate;
	private short status = (short) 1;
	private String note;
	private Set<CampaignActionItem> campaignActionItems = new HashSet<CampaignActionItem>(
			0);

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "campaign_id", nullable = false)
	public Campaign getCampaign() {
		return this.campaign;
	}

	public void setCampaign(Campaign campaign) {
		this.campaign = campaign;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User applicationUser) {
		this.user = applicationUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_id", nullable = false)
	public NeedyCase getNeedyCase() {
		return this.needyCase;
	}

	public void setNeedyCase(NeedyCase needyCase) {
		this.needyCase = needyCase;
	}
	
	@Column(name = "adding_date", length = 23, insertable=false)
	public Date getAddingDate() {
		return this.addingDate;
	}

	public void setAddingDate(Date addingDate) {
		this.addingDate = addingDate;
	}
	
	@Column(name = "status")
	public short getStatus() {
		return status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	@Column(name = "note", length = 3000)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "campaignAction", cascade=CascadeType.ALL)
	public Set<CampaignActionItem> getCampaignActionItems() {
		
		return this.campaignActionItems;
	}

	public void setCampaignActionItems(Set<CampaignActionItem> campaignActionItems) {
		
		this.campaignActionItems = campaignActionItems;
	}
}
