package com.halawa.goodseasons.model.entity;

// Generated Jul 25, 2010 11:25:21 AM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CaseAddress generated by hbm2java
 */
@Entity
@Table(name = "Case_Address")
public class CaseAddress implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4809115180455240309L;
	private Long id;
	private String homeNumber;
	private String streetName;
	private String zoneName;
	private String districtName;
	private String provinceName;
	private Set<NeedyCase> needyCases = new HashSet<NeedyCase>();

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "home_number", nullable = false, length = 10)
	public String getHomeNumber() {
		return this.homeNumber;
	}

	public void setHomeNumber(String homeNumber) {
		this.homeNumber = homeNumber;
	}

	@Column(name = "street_name", nullable = false, length = 100)
	public String getStreetName() {
		return this.streetName;
	}

	public void setStreetName(String streetName) {
		this.streetName = streetName;
	}

	@Column(name = "zone_name", nullable = true, length = 200)
	public String getZoneName() {
		return this.zoneName;
	}

	public void setZoneName(String zoneName) {
		this.zoneName = zoneName;
	}

	@Column(name = "district_name", nullable = false, length = 150)
	public String getDistrictName() {
		return this.districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

	@Column(name = "province_name", length = 100)
	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy="caseAddress")
	public Set<NeedyCase> getNeedyCase() {
		return this.needyCases;
	}

	public void setNeedyCase(Set<NeedyCase> needyCases) {
		this.needyCases = needyCases;
	}
	
	public void addNeedyCase(NeedyCase needyCase) {
		
		this.needyCases.add(needyCase);
	}
}
