package com.halawa.goodseasons.model.entity;

// Generated Jul 25, 2010 11:25:21 AM by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Configuration generated by hbm2java
 */
@Entity
@Table(name = "Configuration", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Configuration implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1258901499989220390L;
	private Long id;
	private String name;
	private String value;
	private String description;


	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "prop_value", nullable = false, length = 150)
	public String getValue() {
		return this.value;
	}

	public void setValue(String propValue) {
		this.value = propValue;
	}

	@Column(name = "description", length = 400)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
