package com.halawa.goodseasons.model.entity;

// Generated Jul 25, 2010 11:25:21 AM by Hibernate Tools 3.2.5.Beta

import java.util.Date;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IrregularCase generated by hbm2java
 */
@Entity
@Table(name = "Irregular_Case")
@DiscriminatorValue("2")
public class IrregularCase extends NeedyCase {

	public IrregularCase() {
		
		super.setType((short) 2);
		super.setDateOfBirth(new Date());
		super.setMaritalStatus("1");
	}
	/**
	 * 
	 */
	private static final long serialVersionUID = 7827550406962244892L;

	
	@Override
	public void setType(short type) {
		
		super.setType((short) 2);
	}
}
