package com.halawa.goodseasons.model.entity;

// Generated Feb 8, 2012 5:07:35 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * NeedyCaseAgent generated by hbm2java
 */
@Entity
@Table(name = "NeedyCase_Agent")
public class NeedyCaseAgent implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private NeedyCase needyCase;
	private String fullName;
	private byte[] personalPhoto;

	public NeedyCaseAgent() {
	}

	public NeedyCaseAgent(Long id, NeedyCase needyCase, String fullName) {
		this.id = id;
		this.needyCase = needyCase;
		this.fullName = fullName;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@OneToOne
    @JoinColumn(name="needyCase_id")
	public NeedyCase getNeedyCase() {
		return this.needyCase;
	}

	public void setNeedyCase(NeedyCase needyCase) {
		this.needyCase = needyCase;
	}

	@Column(name = "full_name", nullable = false, length = 200)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}
	
	@Column(name = "personal_photo", updatable=false)
	@Basic(fetch=FetchType.LAZY)
	public byte[] getPersonalPhoto() {
		return this.personalPhoto;
	}

	public void setPersonalPhoto(byte[] personalPhoto) {
		this.personalPhoto = personalPhoto;
	}
}
