package com.halawa.goodseasons.model.entity;

// Generated Jul 25, 2010 11:25:21 AM by Hibernate Tools 3.2.5.Beta

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NeedyCase generated by hbm2java
 */
@Entity
@Table(name = "Needy_Case")
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn(name="type", discriminatorType=DiscriminatorType.INTEGER)
public class NeedyCase implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1325124297891832940L;
	private Long id;
	private CaseAddress caseAddress;
	private String fullName;
	private String nationalId;
	private Date dateOfBirth;
	private String maritalStatus;
	private short familyPersons = 1;
	private String note;
	private short type;
	private short status;
	private int sectorNumber = 1;
	private String smartCardNumber;
	private String otherInfo;

	private String fullNationalId;
	private Date addingDate;
	private Set<CampaignAction> campaignActions = new HashSet<CampaignAction>(0);
	private NeedyCaseAgent needyCaseAgent;
	private byte[] personalPhoto;
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinColumn(name = "address_id")
	public CaseAddress getCaseAddress() {
		return this.caseAddress;
	}

	public void setCaseAddress(CaseAddress caseAddress) {
		this.caseAddress = caseAddress;
	}

	@Column(name = "full_name", nullable = false)
	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "national_id", nullable = false, length = 14, updatable=true, insertable=true)
	public String getNationalId() {
		return this.nationalId;
	}

	public void setNationalId(String nationalId) {
		this.nationalId = nationalId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_birth", nullable = false, length = 23)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "marital_status", nullable = false, length = 50)
	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	@Column(name = "family_persons", nullable = false)
	public short getFamilyPersons() {
		return this.familyPersons;
	}

	public void setFamilyPersons(short familyPersons) {
		this.familyPersons = familyPersons;
	}

	@Column(name = "note", length = 3000)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "type", updatable=false, insertable=true)
	public short getType() {
		return this.type;
	}

	public void setType(short type) {
		this.type = type;
	}
	
	@Column(name = "status", insertable=false, updatable=true)
	public short getStatus() {
		return status;
	}

	public void setStatus(short status) {
		this.status = status;
	}
	
	@Column(name = "sector_num")
	public int getSectorNumber() {
		return sectorNumber;
	}

	public void setSectorNumber(int sectorNumber) {
		this.sectorNumber = sectorNumber;
	}

	@Column(name = "smart_card_num")
	public String getSmartCardNumber() {
		return smartCardNumber;
	}

	public void setSmartCardNumber(String smartCardNumber) {
		this.smartCardNumber = smartCardNumber;
	}
	
	@Column(name="full_national_id", nullable=true)
	public String getFullNationalId() {
		return fullNationalId;
	}

	public void setFullNationalId(String fullNationalId) {
		this.fullNationalId = fullNationalId;
	}
	
	
	@Column(name="adding_date", nullable=true, insertable=false)
	public Date getAddingDate() {
		return addingDate;
	}

	public void setAddingDate(Date addingDate) {
		this.addingDate = addingDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "needyCase")
	public Set<CampaignAction> getCampaignActions() {
		return this.campaignActions;
	}

	public void setCampaignActions(Set<CampaignAction> campaignActions) {
		this.campaignActions = campaignActions;
	}
	
	@OneToOne(mappedBy = "needyCase", cascade = CascadeType.ALL)
	public NeedyCaseAgent getNeedyCaseAgent() {
		return this.needyCaseAgent;
	}

	public void setNeedyCaseAgent(NeedyCaseAgent needyCaseAgent) {
		this.needyCaseAgent = needyCaseAgent;
		if ( this.needyCaseAgent != null )
			this.needyCaseAgent.setNeedyCase(this);
	}
	
	@Column(name = "personal_photo", updatable=false)
	@Basic(fetch=FetchType.LAZY)
	public byte[] getPersonalPhoto() {
		return this.personalPhoto;
	}

	public void setPersonalPhoto(byte[] personalPhoto) {
		this.personalPhoto = personalPhoto;
	}
	
	@Column(name="other_info", nullable=true)
	public String getOtherInfo() {
		return otherInfo;
	}

	public void setOtherInfo(String otherInfo) {
		this.otherInfo = otherInfo;
	}

}
