package com.halawa.goodseasons.model.entity;

// Generated Jul 25, 2010 11:25:21 AM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Privilege generated by hbm2java
 */
@Entity
@Table(name = "Privilege", uniqueConstraints = @UniqueConstraint(columnNames = {
		"local_name", "status" }))
public class Privilege implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3983124581927575433L;
	private Long id;
	private String displayName;
	private Short status;
	private String localName;
	private String description;
	private short type;
	private Set<UserPrivilege> userPrivileges = new HashSet<UserPrivilege>(0);

	public Privilege() {
	}

	public Privilege(Long id, String displayName, String localName, short type) {
		this.id = id;
		this.displayName = displayName;
		this.localName = localName;
		this.type = type;
	}

	public Privilege(Long id, String displayName, Short status,
			String localName, String description, short type,
			Set<UserPrivilege> userPrivileges) {
		this.id = id;
		this.displayName = displayName;
		this.status = status;
		this.localName = localName;
		this.description = description;
		this.type = type;
		this.userPrivileges = userPrivileges;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "display_name", nullable = false, length = 100)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "status")
	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	@Column(name = "local_name", nullable = false, length = 100)
	public String getLocalName() {
		return this.localName;
	}

	public void setLocalName(String localName) {
		this.localName = localName;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type", nullable = false)
	public short getType() {
		return this.type;
	}

	public void setType(short type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "privilege")
	public Set<UserPrivilege> getUserPrivileges() {
		return this.userPrivileges;
	}

	public void setUserPrivileges(Set<UserPrivilege> userPrivileges) {
		this.userPrivileges = userPrivileges;
	}

}
