package com.halawa.goodseasons.model.entity;

// Generated Jul 25, 2010 11:25:21 AM by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserPrivilege generated by hbm2java
 */
@Entity
@Table(name = "User_Privilege", uniqueConstraints = @UniqueConstraint(columnNames = {
		"user_id", "privilege_id" }))
public class UserPrivilege implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 276161091222520200L;
	private Long id;
	private Privilege privilege;
	private User user;

	public UserPrivilege() {
	}

	public UserPrivilege(Long id, Privilege privilege,
			User applicationUser) {
		this.id = id;
		this.privilege = privilege;
		this.user = applicationUser;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "privilege_id", nullable = false)
	public Privilege getPrivilege() {
		return this.privilege;
	}

	public void setPrivilege(Privilege privilege) {
		this.privilege = privilege;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User applicationUser) {
		this.user = applicationUser;
	}

}
