package com.halawa.goodseasons.model.entity;

// Generated Jul 25, 2010 11:25:21 AM by Hibernate Tools 3.2.5.Beta

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApplicationUser generated by hbm2java
 */
@Entity
@Table(name = "Application_User")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6946577571968889322L;
	private Long id;
	private String username;
	private String password;
	private Short status;
	private Date creationDate;
	private String mobileNumber;
	private Set<UserPrivilege> userPrivileges = new HashSet<UserPrivilege>(0);
	private Set<CampaignAction> campaignActions = new HashSet<CampaignAction>(0);

	public User() {
	}

	public User(Long id, String username, String password) {
		this.id = id;
		this.username = username;
		this.password = password;
	}

	public User(Long id, String username, String password,
			Short status, Date creationDate, String mobileNumber,
			Set<UserPrivilege> userPrivileges,
			Set<CampaignAction> campaignActions) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.status = status;
		this.creationDate = creationDate;
		this.mobileNumber = mobileNumber;
		this.userPrivileges = userPrivileges;
		this.campaignActions = campaignActions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 70)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status")
	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creation_date", length = 23)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "mobile_number", length = 15)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserPrivilege> getUserPrivileges() {
		return this.userPrivileges;
	}

	public void setUserPrivileges(Set<UserPrivilege> userPrivileges) {
		this.userPrivileges = userPrivileges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<CampaignAction> getCampaignActions() {
		return this.campaignActions;
	}

	public void setCampaignActions(Set<CampaignAction> campaignActions) {
		this.campaignActions = campaignActions;
	}

}
